version: '3.5'
services:
    web:
        build: .
        container_name: docker-nodejs-express
        command: npm run dev
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - /app/node_modules